name: mobile_assistant_ia
description: Assistant IA Inov Consulting - Test Technique
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.7
  go_router: ^14.2.0
  intl: ^0.18.1
  table_calendar: ^3.0.9
  cached_network_image: 3.4.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Google_Icon.png
    - assets/images/Git_Icon.png
    - .env